using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Replacer.Tests
{
    public static class Constance
    {
        public const string GetJsonString_EXPECTED = "\"[\\n  \\\"Two roads diverged in a yellow d12324344rgg6f5g6gdf2ddjf,\\\",\\n  \\\"Robert Frost poetAnd sorry I cou1d not trave1 both\\\",\\n  \\\"An other text\\\",\\n  \\\"And be one trave1er, long I stood\\\",\\n  \\\"And 1ooked down one as far as I cou1d\\\",\\n  \\\"Bla-bla-bla-blaaa, just some RANDOM tExT\\\",\\n  \\\"To where it bent in the undergrowth;\\\",\\n  \\\"Then Random text, yeeep the other, as just as fair,\\\",\\n  \\\"And having perhaps parentheses - that is a smart word,\\\",\\n  \\\"Bla-bla-bla-blaaa, just some RANDOM tExT\\\",\\n  \\\"Because it was grassy and wanted wear;\\\",\\n  \\\"An other text\\\",\\n  \\\"An other text\\\",\\n  \\\"Though as for that the passing there\\\",\\n  \\\"Emptry... or NOT! them rea11y about the same,\\\",\\n  \\\"And both that morning equally lay\\\",\\n  \\\"In 1eaves no step had trodden b1ack.\\\",\\n  \\\"Oh, I kept the first for another day!\\\",\\n  \\\"Yet Skooby-dooby-doooo 1eads on to way,\\\",\\n  \\\"Ha-haaa, hacked you.\\\",\\n  \\\"An other text\\\",\\n  \\\"I shall be te11ing this with a sigh\\\",\\n  \\\"sdshdjdskfm sfjsdif jfjfidjf\\\",\\n  \\\"Two roads diverged in a d12324344rgg6f5g6gdf2ddjf, and I\\\",\\n  \\\"I Random text, yeeep the one less traveled by,\\\",\\n  \\\"And that has made a11 the difference.\\\",\\n  \\\"Bla-bla-bla-blaaa, just some RANDOM tExT\\\"\\n]\\n\"";
        public const string ReplaceInJson_HS = "[\n  \"Two roads diverged in a yellow d12324344rgg6f5g6gdf2ddjf,\",\n  \"Robert Frost poetAnd sorry I cou1d not trave1 both\",\n  \"An other text\",\n  \"And be one trave1er, long I stood\",\n  \"And 1ooked down one as far as I cou1d\",\n  \"Bla-bla-bla-blaaa, just some RANDOM tExT\",\n  \"To where it bent in the undergrowth;\",\n  \"Then Random text, yeeep the other, as just as fair,\",\n  \"And having perhaps parentheses - that is a smart word,\",\n  \"Bla-bla-bla-blaaa, just some RANDOM tExT\",\n  \"Because it was grassy and wanted wear;\",\n  \"An other text\",\n  \"An other text\",\n  \"Though as for that the passing there\",\n  \"Emptry... or NOT! them rea11y about the same,\",\n  \"And both that morning equally lay\",\n  \"In 1eaves no step had trodden b1ack.\",\n  \"Oh, I kept the first for another day!\",\n  \"Yet Skooby-dooby-doooo 1eads on to way,\",\n  \"Ha-haaa, hacked you.\",\n  \"An other text\",\n  \"I shall be te11ing this with a sigh\",\n  \"sdshdjdskfm sfjsdif jfjfidjf\",\n  \"Two roads diverged in a d12324344rgg6f5g6gdf2ddjf, and I\",\n  \"I Random text, yeeep the one less traveled by,\",\n  \"And that has made a11 the difference.\",\n  \"Bla-bla-bla-blaaa, just some RANDOM tExT\"\n]\n";
        public const string ReplaceInJson_EXPECTED = "[\n  \"Two roads diverged in a yellow wood,\",\n  \"Robert Frost poetAnd sorry I could not travel both\",\n  \"\",\n  \"And be one traveler, long I stood\",\n  \"And looked down one as far as I could\",\n  \"\",\n  \"To where it bent in the undergrowth;\",\n  \"Then took the other, as just as fair,\",\n  \"And having perhaps the better claim,\",\n  \"\",\n  \"Because it was grassy and wanted wear;\",\n  \"\",\n  \"\",\n  \"Though as for that the passing there\",\n  \"Had worn them really about the same,\",\n  \"And both that morning equally lay\",\n  \"In leaves no step had trodden black.\",\n  \"Oh, I kept the first for another day!\",\n  \"Yet knowing how way leads on to way,\",\n  \"I doubted if I should ever come back.\",\n  \"\",\n  \"I shall be telling this with a sigh\",\n  \"Somewhere ages and ages hence:\",\n  \"Two roads diverged in a wood, and I\",\n  \"I took the one less traveled by,\",\n  \"And that has made all the difference.\",\n  \"\"\n]\n";
        public const string RemoveEscapedQuotes_HS = "[\n  \"Two roads diverged in a yellow wood,\",\n  \"Robert Frost poetAnd sorry I could not travel both\",\n  \"\",\n  \"And be one traveler, long I stood\",\n  \"And looked down one as far as I could\",\n  \"\",\n  \"To where it bent in the undergrowth;\",\n  \"Then took the other, as just as fair,\",\n  \"And having perhaps the better claim,\",\n  \"\",\n  \"Because it was grassy and wanted wear;\",\n  \"\",\n  \"\",\n  \"Though as for that the passing there\",\n  \"Had worn them really about the same,\",\n  \"And both that morning equally lay\",\n  \"In leaves no step had trodden black.\",\n  \"Oh, I kept the first for another day!\",\n  \"Yet knowing how way leads on to way,\",\n  \"I doubted if I should ever come back.\",\n  \"\",\n  \"I shall be telling this with a sigh\",\n  \"Somewhere ages and ages hence:\",\n  \"Two roads diverged in a wood, and I\",\n  \"I took the one less traveled by,\",\n  \"And that has made all the difference.\",\n  \"\"\n]\n";
        public const string RemoveEscapedQuotes_EXPECTED = "Two roads diverged in a yellow wood,\",\n\"Robert Frost poetAnd sorry I could not travel both\",\n\"And be one traveler, long I stood\",\n\"And looked down one as far as I could\",\n\"To where it bent in the undergrowth;\",\n\"Then took the other, as just as fair,\",\n\"And having perhaps the better claim,\",\n\"Because it was grassy and wanted wear;\",\n\"Though as for that the passing there\",\n\"Had worn them really about the same,\",\n\"And both that morning equally lay\",\n\"In leaves no step had trodden black.\",\n\"Oh, I kept the first for another day!\",\n\"Yet knowing how way leads on to way,\",\n\"I doubted if I should ever come back.\",\n\"I shall be telling this with a sigh\",\n\"Somewhere ages and ages hence:\",\n\"Two roads diverged in a wood, and I\",\n\"I took the one less traveled by,\",\n\"And that has made all the difference.";
        public const string WriteJsonToFile_HS = "Two roads diverged in a yellow wood,\",\n\"Robert Frost poetAnd sorry I could not travel both\",\n\"And be one traveler, long I stood\",\n\"And looked down one as far as I could\",\n\"To where it bent in the undergrowth;\",\n\"Then took the other, as just as fair,\",\n\"And having perhaps the better claim,\",\n\"Because it was grassy and wanted wear;\",\n\"Though as for that the passing there\",\n\"Had worn them really about the same,\",\n\"And both that morning equally lay\",\n\"In leaves no step had trodden black.\",\n\"Oh, I kept the first for another day!\",\n\"Yet knowing how way leads on to way,\",\n\"I doubted if I should ever come back.\",\n\"I shall be telling this with a sigh\",\n\"Somewhere ages and ages hence:\",\n\"Two roads diverged in a wood, and I\",\n\"I took the one less traveled by,\",\n\"And that has made all the difference.";

    }
}
